#!/usr/bin/env python3
"""
Golden Farm · animales del Establo, versión PROVISORIA.

Dibuja los 4 animales (alpaca, conejo, toro, jabalí) con pixel art hecho a mano acá,
para poder ver y probar el corral MIENTRAS no está el arte definitivo. No usa PixelLab.

Cada animal es un mapa de texto: una letra por píxel. Se pinta con la paleta cozy del
juego (contorno #241505, como el resto) y se agranda x4 con vecino más cercano, así queda
del mismo tamaño de origen que los demás sprites (~100 px).

    python3 tools/animales-provisorios.py

Cuando llegue el arte bueno: reemplazar los PNG en public/assets/farm y volver a correr
tools/build-atlas.py. El código del juego no cambia (usa las mismas claves).
"""
import os

from PIL import Image

RAIZ = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
FARM = os.path.join(RAIZ, "public", "assets", "farm")
ESCALA = 4

# Paleta cozy del juego. "o" es el contorno oscuro estándar (#241505).
PAL = {
    "o": (36, 21, 5, 255),        # contorno
    ".": (0, 0, 0, 0),            # transparente
    "E": (36, 21, 5, 255),        # ojo
    "s": (0, 0, 0, 70),           # sombra en el piso
}

# animal -> (colores propios, dibujo)
#   B cuerpo · S sombra del cuerpo · L brillo · N nariz/oreja rosada · H cuerno/colmillo
ANIMALES = {
    "alpaca": (
        {"B": (240, 228, 200, 255), "S": (214, 196, 158, 255), "L": (255, 248, 230, 255),
         "N": (200, 150, 140, 255), "H": (255, 248, 230, 255)},
        """
........oooo..........
.......oBLBBo.........
.......oBEBBo.........
.......oNBBBo.........
........oBBo..........
........oBBo..........
........oBBo..........
....ooooBBBoooooo.....
...oBLLBBBBBBBBBBo....
..oBLLBBBBBBBBBBSBo...
..oBBBBBBBBBBBBBSBo...
..oBBSSBBBBBBBSSBBo...
...ooBoooooooBooooo...
.....oBo.....oBo......
.....oBo.....oBo......
.....ooo.....ooo......
....ssss....ssss......
"""),
    "conejo": (
        {"B": (245, 242, 232, 255), "S": (214, 208, 192, 255), "L": (255, 255, 250, 255),
         "N": (240, 153, 123, 255), "H": (255, 255, 250, 255)},
        """
.....oo......oo.......
....oNBo....oBNo......
....oNBo....oBNo......
....oNBo....oBNo......
....oBBoooooBBo.......
...ooBBBBBBBBBoo......
..oBLLBBBBBBBBBBo.....
..oBLBBEBBBBBBBSBo....
..oBBBBBBBBBBBBSBo....
..oBBBNBBBBBBSSBBo....
...oBBBBBBBBBBBBo.....
....ooBooooooBoo......
.....oBo....oBo.......
.....ooo....ooo.......
.....ssss...ssss......
"""),
    "toro": (
        {"B": (138, 90, 51, 255), "S": (95, 58, 30, 255), "L": (176, 122, 74, 255),
         "N": (240, 153, 123, 255), "H": (240, 232, 200, 255)},
        """
...oHo......oHo.......
..oHHo......oHHo......
..oHBoooooooBHo.......
...oBBLBBBBBBBo.......
...oBEBBBBBBEBo.......
...oBBBNNNBBBBo.......
....oooBBBooooo.......
..ooooBBBBBoooooo.....
.oBLLBBBBBBBBBBBBo....
.oBLBBBBBBBBBBBBSBo...
.oBBBBBBBBBBBBBBSBo...
.oBBSSBBBBBBBBSSBBo...
..ooBoooooooooBoooo...
....oBo......oBo......
....oBo......oBo......
....ooo......ooo......
...ssss.....ssss......
"""),
    "jabali": (
        {"B": (95, 94, 90, 255), "S": (68, 68, 65, 255), "L": (136, 135, 128, 255),
         "N": (36, 21, 5, 255), "H": (240, 232, 200, 255)},
        """
......................
....ooo...............
...oBBBoooooo.........
..oBEBBBBBBBBoo.......
..oBBBNNBBBBBBBoo.....
.oHBBNNNBBBBBBBBBo....
.oHoBBBBBBLLBBBBBBo...
..ooBBBBBBLBBBBBBSBo..
...oBBBBBBBBBBBBBSBo..
...oBBSSBBBBBBBSSBBo..
....ooBoooooooBooooo..
......oBo....oBo......
......oBo....oBo......
......ooo....ooo......
.....ssss...ssss......
"""),
}


def dibujar(nombre, colores, mapa):
    filas = [f for f in mapa.strip("\n").split("\n")]
    alto = len(filas)
    ancho = max(len(f) for f in filas)
    im = Image.new("RGBA", (ancho, alto), (0, 0, 0, 0))
    px = im.load()
    pal = dict(PAL)
    pal.update(colores)
    for y, fila in enumerate(filas):
        for x, ch in enumerate(fila):
            c = pal.get(ch)
            if c and c[3]:
                px[x, y] = c
    im = im.resize((ancho * ESCALA, alto * ESCALA), Image.NEAREST)
    ruta = os.path.join(FARM, "animal_" + nombre + ".png")
    im.save(ruta)
    return ruta, im.size


if __name__ == "__main__":
    for nombre, (colores, mapa) in ANIMALES.items():
        ruta, tam = dibujar(nombre, colores, mapa)
        print("animal_%s.png  %sx%s" % (nombre, tam[0], tam[1]))
    print("\nListo. Ahora: python3 tools/build-atlas.py  y subir el ?v= del atlas en boot.js")
